### ISSUE TITLE
哔哩哔哩无法触发移动免流

### ISSUE THREAD

**Issue by Semidio** [onewayticket255/Surge-Script#11]
AND,((USER-AGENT,bili*), (DOMAIN,wap.cmpassport.com)),DIRECT

测试环境: 江苏移动4G

**Comment by onewayticket255** [comment]
像b站官方移动免流我没怎么研究过,  不过可以试试sample-obfs  指定host为hdslb.com

**Comment by Semidio** [comment]
> 像b站官方移动免流我没怎么研究过, 不过可以试试sample-obfs 指定host为hdslb.com

额，我指的是在购买了移动B站流量包的情况下，如果不将apm-misaka.biliapi.net，rp.hpplay.cn以及wap.cmpassport.com放行DIRECT的话，无法使用B站流量包里的流量。

**Comment by onewayticket255** [comment]
移动B站流量包很小众特殊， 暂时不会修改master 规则

**Comment by Semidio** [comment]
> 移动B站流量包很小众特殊， 暂时不会修改master 规则

其实只需要把
AND,((USER-AGENT,bili*), (NOT,((DOMAIN-SUFFIX,bilibili.com))),(NOT,((DOMAIN-SUFFIX,hdslb.com)))),REJECT-TINYGIF
改成
AND,((USER-AGENT,bili*), (NOT,((DOMAIN-SUFFIX,bilibili.com))),(NOT,((DOMAIN-SUFFIX,hdslb.com))), (NOT,((DOMAIN,wap.cmpassport.com)))),REJECT-TINYGIF
应该就没问题了
