### ISSUE TITLE
bilibili左上角头像无法正常显示

### ISSUE THREAD

**Issue by madokaxiaoyuan** [onewayticket255/Surge-Script#12]
bilibili 最新版(5.52)，去广告脚本生效后，左上角头像无法正常显示。

**Comment by madokaxiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/45760201/71433969-3a11c780-271d-11ea-9846-ac4e13459c92.png)

**Comment by madokaxiaoyuan** [comment]
![QQ截图20191225134904](https://user-images.githubusercontent.com/45760201/71433991-5c0b4a00-271d-11ea-89d4-98c933deaa56.png)

**Comment by onewayticket255** [comment]
这个地方我之前研究过，这个图片加载和刷新机制很奇怪 (可能是第一个版本加这个的原因)
想弄清楚，非常麻烦和耗费时间

如果能弄清楚，给我反馈下

**Comment by madokaxiaoyuan** [comment]
嗯，好的，谢谢。这个当前不影响使用的。
