### ISSUE TITLE
bilibili脚本部分失效了

### ISSUE THREAD

**Issue by jeizas** [onewayticket255/Surge-Script#14]
![IMG_3252](https://user-images.githubusercontent.com/12405225/75209186-9e521580-57b8-11ea-8a70-abbd57bc0b40.PNG)
这个怎么弄下呢

**Comment by onewayticket255** [comment]
不能评论的视频 会有这个错误。我对不能评论的视频也没什么兴趣。

**Comment by jeizas** [comment]
大佬豪横
