### ISSUE TITLE
可以增加网页版知乎去除登录弹窗功能吗？

### ISSUE THREAD

**Issue by sky003-Max** [onewayticket255/Surge-Script#16]
在手机上观看知乎电脑网页版，会有登录弹窗，能不能用surge的规则或者js去除掉这个弹窗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by onewayticket255** [comment]
直接跳转到app内部看，反正没广告了
