### ISSUE TITLE
[Rule]一条规则误杀热榜页面

### ISSUE THREAD

**Issue by kyle1an** [onewayticket255/Surge-Script#3]
[Rule] 里如果不删掉下面规则，知乎热榜会变成空白。如果删掉，时间线会有广告。
AND,((USER-AGENT,osee2*), (NOT,((DOMAIN,api.zhihu.com))), (NOT,((DOMAIN,lens.zhihu.com))), (NOT,((DOMAIN,static.zhihu.com))), (NOT,((DOMAIN,www.zhihu.com))), (NOT,((DOMAIN-SUFFIX,zhimg.com)))),REJECT

**Comment by mlyxshi** [comment]
我这里没问题

**Comment by kyle1an** [comment]
谢谢。应该确实是我配置的问题。我新建一个空白配置文件只放zhihu的规则完全没问题。
