### ISSUE TITLE
好像B站的失效了  开启了app里面加载不出来数据

### ISSUE THREAD

**Issue by szweee** [onewayticket255/Surge-Script#5]

**Comment by scott90578** [comment]
我也遇到了，这个问题

**Comment by scott90578** [comment]
我这测试删除 ，这些后 可以正常使用
//BiliBili
DOMAIN,dataflow.biliapi.com,REJECT-TINYGIF
DOMAIN,data.bilibili.com,REJECT-TINYGIF
DOMAIN,thirdparty.biliapi.com,REJECT
DOMAIN,cm.bilibili.com,REJECT
URL-REGEX,https://app.bilibili.com/x/v2/param,REJECT
URL-REGEX,https://app.bilibili.com/x/resource/abtest,REJECT
URL-REGEX,http://app.bilibili.com/x/v2/dataflow/report,REJECT-TINYGIF
URL-REGEX,https://app.bilibili.com/x/v2/search/(defaultword|hot|recommend|resource),REJECT
URL-REGEX,https://app.bilibili.com/x/v2/rank.*rid=(168|5),REJECT
URL-REGEX,https://api.bilibili.com/pgc/season/rank/cn,REJECT
AND,((USER-AGENT,bili*), (NOT,((DOMAIN-SUFFIX,bilibili.com))), (NOT,((DOMAIN-SUFFIX,hdslb.com)))),REJECT

http-response https://app.bilibili.com/x/resource/show/tab requires-body=true,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20tab.js
http-response https://app.bilibili.com/x/v2/feed requires-body=true,script-path=https://raw.githubusercontent.com/onewayticket255/Surge-Script/master/surge%20bilibili%20feed.js
